"""
Mud98Bot Configuration Module.

Centralizes all configuration constants including room VNUMs, route definitions,
behavior priorities, and gameplay thresholds.
"""

from .rooms import (
    # Temple/recall
    TEMPLE_ROOM,
    RECALL_ROOM,
    
    # Cage/patrol rooms
    CENTRAL_ROOM,
    NORTH_CAGE_ROOM,
    SOUTH_CAGE_ROOM,
    EAST_CAGE_ROOM,
    WEST_CAGE_ROOM,
    CAGE_ROOMS,
    PATROL_ROOMS,
    
    # Training rooms
    TRAIN_ROOM,
    PRACTICE_ROOM,
    
    # Shopping rooms
    SHOP_ROOM,
    INTERMEDIATE_ROOM,
    
    # Routes
    ROUTE_TO_CAGE_ROOM,
    ROUTE_TO_NORTH_CAGE,
    ROUTE_TO_SOUTH_CAGE,
    ROUTE_TO_EAST_CAGE,
    ROUTE_TO_WEST_CAGE,
    ROUTE_TO_TRAIN_ROOM,
    ROUTE_TO_PRACTICE_ROOM,
    
    # Patrol sequence
    PATROL_SEQUENCE,
    CAGE_EXIT_DIRECTIONS,
)

from .constants import (
    # Behavior priorities
    PRIORITY_DEATH_RECOVERY,
    PRIORITY_SURVIVE,
    PRIORITY_RECALL,
    PRIORITY_COMBAT,
    PRIORITY_LOOT,
    PRIORITY_HEAL,
    PRIORITY_BOT_RESET,
    PRIORITY_TRAIN,
    PRIORITY_PRACTICE,
    PRIORITY_ATTACK,
    PRIORITY_BUY_SUPPLIES,
    PRIORITY_PATROL,
    PRIORITY_NAVIGATE,
    PRIORITY_EXPLORE,
    PRIORITY_RETURN_TO_CAGE,
    PRIORITY_SHOP,
    PRIORITY_IDLE,
    
    # HP/Mana/Movement thresholds
    DEFAULT_FLEE_HP_PERCENT,
    DEFAULT_REST_HP_PERCENT,
    DEFAULT_REST_MANA_PERCENT,
    DEFAULT_REST_MOVE_PERCENT,
    CRITICAL_HP_PERCENT,
    CRITICAL_MOVE_PERCENT,
    
    # Combat thresholds
    MAX_LEVEL_DIFFERENCE,
    MIN_ATTACK_HP_PERCENT,
    
    # Timing
    DEFAULT_TICK_DELAY,
    PATROL_LINGER_TICKS,
    MAX_FLEE_ATTEMPTS,
    MAX_WANDER_ATTEMPTS,
    
    # Shopping
    MIN_SHOPPING_MONEY,
    
    # Text buffer
    MAX_TEXT_BUFFER_LINES,
    
    # Practice defaults
    DEFAULT_PRACTICE_PER_SKILL,
    DEFAULT_PRACTICE_SKILLS,
)

__all__ = [
    # Room VNUMs
    'TEMPLE_ROOM', 'RECALL_ROOM',
    'CENTRAL_ROOM', 'NORTH_CAGE_ROOM', 'SOUTH_CAGE_ROOM', 'EAST_CAGE_ROOM', 'WEST_CAGE_ROOM',
    'CAGE_ROOMS', 'PATROL_ROOMS',
    'TRAIN_ROOM', 'PRACTICE_ROOM',
    'SHOP_ROOM', 'INTERMEDIATE_ROOM',
    
    # Routes
    'ROUTE_TO_CAGE_ROOM', 'ROUTE_TO_NORTH_CAGE', 'ROUTE_TO_SOUTH_CAGE',
    'ROUTE_TO_EAST_CAGE', 'ROUTE_TO_WEST_CAGE',
    'ROUTE_TO_TRAIN_ROOM', 'ROUTE_TO_PRACTICE_ROOM',
    'PATROL_SEQUENCE', 'CAGE_EXIT_DIRECTIONS',
    
    # Priorities
    'PRIORITY_DEATH_RECOVERY', 'PRIORITY_SURVIVE', 'PRIORITY_RECALL',
    'PRIORITY_COMBAT', 'PRIORITY_LOOT', 'PRIORITY_HEAL',
    'PRIORITY_BOT_RESET', 'PRIORITY_TRAIN', 'PRIORITY_PRACTICE',
    'PRIORITY_ATTACK', 'PRIORITY_BUY_SUPPLIES', 'PRIORITY_PATROL',
    'PRIORITY_NAVIGATE', 'PRIORITY_EXPLORE', 'PRIORITY_RETURN_TO_CAGE',
    'PRIORITY_SHOP', 'PRIORITY_IDLE',
    
    # Thresholds
    'DEFAULT_FLEE_HP_PERCENT', 'DEFAULT_REST_HP_PERCENT',
    'DEFAULT_REST_MANA_PERCENT', 'DEFAULT_REST_MOVE_PERCENT',
    'CRITICAL_HP_PERCENT', 'CRITICAL_MOVE_PERCENT',
    'MAX_LEVEL_DIFFERENCE', 'MIN_ATTACK_HP_PERCENT',
    
    # Timing
    'DEFAULT_TICK_DELAY', 'PATROL_LINGER_TICKS',
    'MAX_FLEE_ATTEMPTS', 'MAX_WANDER_ATTEMPTS',
    
    # Shopping
    'MIN_SHOPPING_MONEY',
    
    # Misc
    'MAX_TEXT_BUFFER_LINES',
    'DEFAULT_PRACTICE_PER_SKILL', 'DEFAULT_PRACTICE_SKILLS',
]
