#!/bin/bash

build_cfg="Debug"
bench=""

for arg in "$@" 
do
if [[ ${arg,,} == "release" ]] || [[ ${arg,,} == "rel" ]]
    then
        build_cfg="Release"
    elif [[ ${arg,,} == "debug" ]] || [[ ${arg,,} == "deb" ]]
    then
        build_cfg="Debug"
    elif [[ ${arg,,} == "relwithdebinfo" ]] || [[ ${arg,,} == "relwithdeb" ]] || [[ ${arg,,} == "reldeb" ]]
    then
        build_cfg="RelWithDebInfo"
    elif [[ ${arg,,} == "benchonly" ]]
    then
        bench="-B"
    else
        echo "Unknown argument '${arg,,}'."
        exit
    fi
done

./.build/$build_cfg/Mud98 --area-dir=../area --port=4000 $bench

