#!/bin/bash

for ARG in "$@" 
do
    if [[ ${ARG,,} == "clean" ]]
    then
        rm -f *.key
        rm -f *.csr
        rm -f *.crt
        rm -f *.pem
    else
        echo "Unknown argument '${ARG,,}'."
        exit
    fi

done

if [ ! -f "mud98.key" ] || [ ! -f "mud98.csr" ]; then
    echo "Creating private key and signing request."
    openssl req -newkey rsa:2048 -nodes -keyout mud98.key -out mud98.csr
fi

if [ ! -f "mud98.crt" ]; then
    echo "Creating self-signed certificate."
    openssl x509 -signkey mud98.key -in mud98.csr -req -days 365 -out mud98.crt
fi

if [ ! -f "mud98.pem" ]; then
    echo "Creating PEM file."
    openssl x509 -in mud98.crt -out mud98.pem
fi

echo "Server's self-signed cert:"
openssl x509 -in mud98.pem -noout -text

