#!/bin/bash

for ARG in "$@" 
do
    if [[ ${ARG,,} == "clean" ]]
    then
        rm -f *.pem
    else
        echo "Unknown argument '${ARG,,}'."
        exit
    fi

done

if [ ! -f "ca-key.pem" ] || [ ! -f "ca-cert.pem" ]; then
    echo "Creating CA self-signed cert."
    openssl req -newkey rsa:2048 -nodes -keyout ca-key.pem -x509 -days 365 -out ca-cert.pem
fi

echo "CA self-signed cert:"
openssl x509 -in ca-cert.pem -noout -text

if [ ! -f "server-key.pem" ] || [ ! -f "server-req.pem" ]; then
    echo "Creating server key and certificate request."
    openssl req -newkey rsa:2048 -nodes -keyout server-key.pem -out server-req.pem
fi

if [ ! -f "server-cert.pem" ]; then
    echo "Signing server certificate."
    openssl x509 -req -in server-req.pem -days 60 -CA ca-cert.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem
fi

echo "Server's signed cert:"
openssl x509 -in server-cert.pem -noout -text
