#!/bin/bash

for ARG in "$@" 
do
    if [[ ${ARG,,} == "clean" ]]
    then
        rm -f *.key
        rm -f *.csr
        rm -f *.crt
        rm -f *.pem
    else
        echo "Unknown argument '${ARG,,}'."
        exit
    fi

done

if [ ! -f "rom-mud.key" ] || [ ! -f "rom-mud.csr" ]; then
    echo "Creating private key and signing request."
    openssl req -newkey rsa:2048 -nodes -keyout rom-mud.key -out rom-mud.csr
fi

if [ ! -f "rom-mud.crt" ]; then
    echo "Creating self-signed certificate."
    openssl x509 -signkey rom-mud.key -in rom-mud.csr -req -days 365 -out rom-mud.crt
fi

if [ ! -f "rom-mud.pem" ]; then
    echo "Creating PEM file."
    openssl x509 -in rom-mud.crt -out rom-mud.pem
fi

echo "Server's self-signed cert:"
openssl x509 -in rom-mud.pem -noout -text

